# Generated by Django 4.1.3 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduComplain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='programme',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
