# Generated by Django 4.1.3 on 2024-01-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduComplain', '0003_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reg_no',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
