# Generated by Django 4.2.7 on 2024-02-10 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EduComplain', '0006_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('meeting_datetime', models.DateTimeField()),
                ('google_meet_link', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
