# Generated by Django 4.2.7 on 2024-02-23 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EduComplain', '0007_staffmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='complaint_reports/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='accepter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
