# Generated by Django 4.2.7 on 2024-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduComplain', '0008_complaint_report_alter_complaint_accepter'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmeeting',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
